import { describe, it, expect } from 'vitest';
import fc from 'fast-check';

/**
 * Property 1: Music engine voice count and detune bounds
 * Validates: Requirements 1.3
 *
 * For any chord voicing generated by generateChordVoices, the number of voices
 * SHALL be between 2 and 4 (inclusive), and each voice's detune value SHALL be
 * between 2 and 8 cents (inclusive).
 */

// Constants copied from app.js (pure function, tested in isolation)
const MUSIC_VOICES_MIN = 2;
const MUSIC_VOICES_MAX = 4;
const MUSIC_DETUNE_MIN = 2;    // cents
const MUSIC_DETUNE_MAX = 8;    // cents

function generateChordVoices(chordFrequencies) {
  const voiceCount = MUSIC_VOICES_MIN + Math.floor(
    Math.random() * (MUSIC_VOICES_MAX - MUSIC_VOICES_MIN + 1)
  );
  const voices = [];
  for (let i = 0; i < voiceCount; i++) {
    const freq = chordFrequencies[i % chordFrequencies.length];
    const detune = MUSIC_DETUNE_MIN + Math.random() * (MUSIC_DETUNE_MAX - MUSIC_DETUNE_MIN);
    voices.push({
      frequency: freq,
      detune: detune,
      waveType: i % 2 === 0 ? 'sine' : 'triangle'
    });
  }
  return voices;
}

describe('generateChordVoices - Property 1: Music engine voice count and detune bounds', () => {
  /**
   * **Validates: Requirements 1.3**
   */

  it('always produces between 2 and 4 voices (inclusive)', () => {
    fc.assert(
      fc.property(
        fc.array(fc.float({ min: 20, max: 2000, noNaN: true }), { minLength: 1, maxLength: 8 }),
        (chordFrequencies) => {
          const voices = generateChordVoices(chordFrequencies);
          expect(voices.length).toBeGreaterThanOrEqual(2);
          expect(voices.length).toBeLessThanOrEqual(4);
        }
      ),
      { numRuns: 200 }
    );
  });

  it('every voice has a detune value between 2 and 8 cents (inclusive)', () => {
    fc.assert(
      fc.property(
        fc.array(fc.float({ min: 20, max: 2000, noNaN: true }), { minLength: 1, maxLength: 8 }),
        (chordFrequencies) => {
          const voices = generateChordVoices(chordFrequencies);
          for (const voice of voices) {
            expect(voice.detune).toBeGreaterThanOrEqual(2);
            expect(voice.detune).toBeLessThanOrEqual(8);
          }
        }
      ),
      { numRuns: 200 }
    );
  });

  it('every voice has a waveType of either sine or triangle', () => {
    fc.assert(
      fc.property(
        fc.array(fc.float({ min: 20, max: 2000, noNaN: true }), { minLength: 1, maxLength: 8 }),
        (chordFrequencies) => {
          const voices = generateChordVoices(chordFrequencies);
          for (const voice of voices) {
            expect(['sine', 'triangle']).toContain(voice.waveType);
          }
        }
      ),
      { numRuns: 200 }
    );
  });

  it('every voice has a frequency that matches one from the input array', () => {
    fc.assert(
      fc.property(
        fc.array(fc.float({ min: 20, max: 2000, noNaN: true }), { minLength: 1, maxLength: 8 }),
        (chordFrequencies) => {
          const voices = generateChordVoices(chordFrequencies);
          for (const voice of voices) {
            expect(chordFrequencies).toContain(voice.frequency);
          }
        }
      ),
      { numRuns: 200 }
    );
  });
});
